/* CATÁLOGO FOLHAS & ERVAS — um produto por linha.
   c   = código REF            n = nome              cat = categoria (igual à lista "cats")
   d   = descrição curta       b = benefícios        u   = modo de uso
   a   = aviso (ou null)       f = fontes            tag = selo (ex.: "Novo") ou null
   img = foto (fotos/CODIGO.jpg, quadrada)           id  = identificador único (normalmente = código)
   step = de quanto em quanto vende (padrão 50)      unit = "un" se for por unidade
   indisponivel: true  → aparece como indisponível   oculto: true → some do catálogo  */
window.FE_DATA = {
  "cats": ["Temperos","Farinhas, Sementes e Pós","Chás e Ervas","Petiscos e Castanhas","Drágeas e Guloseimas"],
  "fontes": {
 "ff": [
  "ANVISA – Formulário de Fitoterápicos da Farmacopeia Brasileira, 2ª ed.",
  "https://www.gov.br/anvisa/pt-br/assuntos/farmacopeia/formulario-fitoterapico"
 ],
 "taco": [
  "TACO – Tabela Brasileira de Composição de Alimentos (NEPA/Unicamp)",
  "https://nepa.unicamp.br/tabela-brasileira-de-composicao-de-alimentos-4a-edicao/"
 ],
 "guia": [
  "Ministério da Saúde – Guia Alimentar para a População Brasileira",
  "https://www.gov.br/saude/pt-br/assuntos/saude-brasil/publicacoes-para-promocao-a-saude/guia_alimentar_populacao_brasileira_2ed.pdf/view"
 ],
 "oms_sal": [
  "OMS – Redução do consumo de sal (menos de 5 g/dia)",
  "https://www.who.int/news-room/fact-sheets/detail/salt-reduction"
 ],
 "efsa": [
  "União Europeia – Registro oficial de alegações de saúde (EFSA)",
  "https://food.ec.europa.eu/food-safety/labelling-and-nutrition/nutrition-and-health-claims/eu-register-health-claims_en"
 ],
 "embrapa_bv": [
  "Embrapa – Farinha de banana verde: alimento nutritivo e rico em amido resistente",
  "https://www.embrapa.br/en/busca-de-publicacoes/-/publicacao/1083250/farinha-de-banana-verde-alimento-nutritivo-e-rico-em-amido-resistente"
 ],
 "ods_se": [
  "NIH – Office of Dietary Supplements: Selênio",
  "https://ods.od.nih.gov/factsheets/Selenium-Consumer/"
 ],
 "nccih_turmeric": [
  "NIH/NCCIH – Cúrcuma (Turmeric)",
  "https://www.nccih.nih.gov/health/turmeric"
 ],
 "nccih_ginger": [
  "NIH/NCCIH – Gengibre (Ginger)",
  "https://www.nccih.nih.gov/health/ginger"
 ],
 "nccih_cinnamon": [
  "NIH/NCCIH – Canela (Cinnamon)",
  "https://www.nccih.nih.gov/health/cinnamon"
 ],
 "nccih_greentea": [
  "NIH/NCCIH – Chá verde (Green Tea)",
  "https://www.nccih.nih.gov/health/green-tea"
 ],
 "nccih_chamomile": [
  "NIH/NCCIH – Camomila (Chamomile)",
  "https://www.nccih.nih.gov/health/chamomile"
 ],
 "nccih_lavender": [
  "NIH/NCCIH – Lavanda (Lavender)",
  "https://www.nccih.nih.gov/health/lavender"
 ],
 "nccih_flax": [
  "NIH/NCCIH – Linhaça (Flaxseed)",
  "https://www.nccih.nih.gov/health/flaxseed-and-flaxseed-oil"
 ],
 "nccih_fenugreek": [
  "NIH/NCCIH – Feno-grego (Fenugreek)",
  "https://www.nccih.nih.gov/health/fenugreek"
 ],
 "nccih_ginseng": [
  "NIH/NCCIH – Ginseng asiático",
  "https://www.nccih.nih.gov/health/asian-ginseng"
 ],
 "rotulo": [
  "Rótulo e ficha técnica do fornecedor",
  null
 ],
 "ema": [
  "EMA – Agência Europeia de Medicamentos: monografias de plantas medicinais (HMPC)",
  "https://www.ema.europa.eu/en/human-regulatory-overview/herbal-medicinal-products"
 ],
 "nccih_hibiscus": [
  "NIH/NCCIH – Hibisco (Hibiscus)",
  "https://www.nccih.nih.gov/health/hibiscus"
 ],
 "msk_maca": [
  "Memorial Sloan Kettering – About Herbs: Maca",
  "https://www.mskcc.org/cancer-care/integrative-medicine/herbs/maca"
 ],
 "ods_exercise": [
  "NIH – Office of Dietary Supplements: Suplementos e desempenho físico (inclui Tribulus)",
  "https://ods.od.nih.gov/factsheets/ExerciseAndAthleticPerformance-Consumer/"
 ],
 "ods_ca": [
  "NIH – Office of Dietary Supplements: Cálcio",
  "https://ods.od.nih.gov/factsheets/Calcium-Consumer/"
 ],
 "ods_mg": [
  "NIH – Office of Dietary Supplements: Magnésio",
  "https://ods.od.nih.gov/factsheets/Magnesium-Consumer/"
 ],
 "efsa_carvao": [
  "EFSA Journal 2011;9(4):2049 – Carvão ativado e redução de gases intestinais",
  "https://efsa.onlinelibrary.wiley.com/doi/10.2903/j.efsa.2011.2049"
 ],
 "ncbi_carvao": [
  "NIH/NCBI StatPearls – Carvão ativado (Activated Charcoal)",
  "https://www.ncbi.nlm.nih.gov/books/NBK482294/"
 ],
 "sem_mono": [
  "Sem monografia oficial da ANVISA ou da EMA: uso popular, sem comprovação científica suficiente",
  null
 ]
},
  "products": [
    {"c":"440","n":"Açafrão (Cúrcuma)","cat":"Temperos","d":"Raiz de Curcuma longa seca e moída. Cor amarela intensa e sabor terroso, levemente amargo. Contém curcuminoides, os compostos que dão a cor.","b":["Uso tradicional reconhecido pela ANVISA como auxiliar da digestão (sensação de peso após refeições)","Dá cor e sabor a arroz, ovos, sopas e caldos sem corantes artificiais","A pimenta-do-reino aumenta a absorção da curcumina"],"u":"1/2 a 1 colher (chá) no preparo de arroz, legumes, ovos ou golden milk.","f":["ff","nccih_turmeric"],"a":null,"tag":null,"img":"fotos/440.jpg","id":"440"},
    {"c":"1129","n":"Alho Granulado","cat":"Temperos","d":"Alho desidratado em grânulos. Mais aromático que o pó e mantém textura no preparo.","b":["Praticidade: substitui o alho fresco sem descascar ou picar","Longa durabilidade em pote bem fechado","Tempera sem precisar de caldos industrializados"],"u":"1/2 colher (chá) equivale a cerca de 1 dente de alho.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/1129.jpg","id":"1129"},
    {"c":"590","n":"Alho em Pó","cat":"Temperos","d":"Alho desidratado e moído bem fino. Dissolve fácil em molhos, marinadas e massas.","b":["Sabor de alho distribuído por igual","Ideal para temperos secos, pães e pipoca","Reduz a dependência de temperos prontos com muito sódio"],"u":"Use aos poucos: é mais concentrado que o alho fresco.","f":["guia"],"a":null,"tag":null,"img":"fotos/590.jpg","id":"590"},
    {"c":"433","n":"Alho Frito","cat":"Temperos","d":"Lâminas ou pedaços de alho fritos e crocantes, prontos para finalizar pratos.","b":["Crocância e aroma de alho dourado na hora","Finaliza arroz, feijão, sopas e saladas","Pronto para usar, sem fritura em casa"],"u":"Adicione no final do preparo para manter a crocância.","f":["guia"],"a":null,"tag":null,"img":"fotos/433.jpg","id":"433"},
    {"c":"418","n":"Amaciante de Carne","cat":"Temperos","d":"Mistura em pó para amaciar e temperar carnes antes do preparo. Composição conforme rótulo do fornecedor.","b":["Carnes mais macias em cortes mais firmes","Tempera e amacia em uma só etapa","Prático para o dia a dia"],"u":"Polvilhe sobre a carne e deixe agir 15 a 30 min. Contém sal: reduza o sal da receita.","f":["rotulo","oms_sal"],"a":null,"tag":null,"img":"","id":"418"},
    {"c":"60","n":"Bicarbonato de Sódio","cat":"Temperos","d":"Sal de sódio em pó fino (NaHCO₃), usado como fermento químico e em limpeza doméstica.","b":["Ajuda massas a crescer quando combinado a ingredientes ácidos (iogurte, limão)","Usado em receitas de pães rápidos, bolos e biscoitos","Aliado da limpeza doméstica: remove odores e gordura"],"u":"Em receitas: pequenas quantidades (1 colher de chá por receita). Não use como remédio sem orientação médica.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/60.jpg","id":"60"},
    {"c":"1451","n":"Bife Acebolado","cat":"Temperos","d":"Tempero seco pronto com cebola e especiarias, pensado para bifes e carnes na chapa. Composição conforme rótulo.","b":["Sabor de bife acebolado sem cortar cebola","Prático para carnes, frango e legumes salteados","Rende bem: pouca quantidade tempera muito"],"u":"Tempere a carne 10 min antes de grelhar.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1451.jpg","id":"1451"},
    {"c":"370","n":"Caldo de Carne (em pó)","cat":"Temperos","d":"Caldo em pó sabor carne, a granel. Composição conforme rótulo do fornecedor.","b":["Realça sopas, molhos e risotos","Dosagem livre: você usa só o necessário","Prático para o dia a dia"],"u":"Use com moderação: caldos em pó costumam ter muito sódio.","f":["rotulo","oms_sal"],"a":null,"tag":null,"img":"fotos/370.jpg","id":"370"},
    {"c":"902","n":"Caldo de Costela (em pó)","cat":"Temperos","d":"Caldo em pó sabor costela, a granel. Composição conforme rótulo do fornecedor.","b":["Sabor encorpado para feijão, caldos e ensopados","Dosagem livre, sem tabletes","Prático para o dia a dia"],"u":"Use com moderação: caldos em pó costumam ter muito sódio.","f":["rotulo","oms_sal"],"a":null,"tag":null,"img":"fotos/902.jpg","id":"902"},
    {"c":"319","n":"Caldo de Galinha (em pó)","cat":"Temperos","d":"Caldo em pó sabor galinha, a granel. Composição conforme rótulo do fornecedor.","b":["Realça arroz, sopas, risotos e molhos brancos","Dosagem livre, sem tabletes","Prático para o dia a dia"],"u":"Use com moderação: caldos em pó costumam ter muito sódio.","f":["rotulo","oms_sal"],"a":null,"tag":null,"img":"fotos/319.jpg","id":"319"},
    {"c":"1024","n":"Cebola Crispy","cat":"Temperos","d":"Cebola frita crocante, pronta para finalizar pratos.","b":["Crocância e sabor adocicado de cebola dourada","Finaliza saladas, hambúrgueres, purês e sopas","Pronta para usar"],"u":"Adicione no final, sobre o prato já montado.","f":["guia"],"a":null,"tag":null,"img":"fotos/1024.jpg","id":"1024"},
    {"c":"963","n":"Cebola em Flocos","cat":"Temperos","d":"Cebola desidratada em flocos. Reidrata no preparo e devolve sabor de cebola refogada.","b":["Substitui a cebola fresca em molhos, sopas e carnes","Longa durabilidade","Sem choro na cozinha"],"u":"1 colher (sopa) equivale a cerca de 1/2 cebola média.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/963.jpg","id":"963"},
    {"c":"490","n":"Chimichurri com Barbecue","cat":"Temperos","d":"Mistura de ervas desidratadas no estilo chimichurri com toque defumado de barbecue. Composição conforme rótulo.","b":["Sabor de churrasco para carnes, frango e legumes","Ervas e especiarias em um só tempero","Pode ser hidratado com azeite para molho"],"u":"Hidrate 2 colheres (sopa) em azeite e um pouco de vinagre ou use seco.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/490.jpg","id":"490"},
    {"c":"919","n":"Chimichurri com Limão","cat":"Temperos","d":"Chimichurri de ervas desidratadas com notas cítricas de limão. Composição conforme rótulo.","b":["Frescor cítrico para peixes, frango e saladas","Ervas e especiarias em um só tempero","Ótimo como marinada"],"u":"Misture com azeite e deixe descansar 15 min antes de servir.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/919.jpg","id":"919"},
    {"c":"765","n":"Chimichurri Defumado","cat":"Temperos","d":"Chimichurri de ervas desidratadas com páprica defumada. Composição conforme rótulo.","b":["Sabor de brasa mesmo sem churrasqueira","Combina com carnes, batatas e legumes assados","Pode ser usado seco ou hidratado"],"u":"Polvilhe antes de assar ou hidrate com azeite.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/765.jpg","id":"765"},
    {"c":"557","n":"Chimichurri Picante","cat":"Temperos","d":"Chimichurri de ervas desidratadas com pimenta. Composição conforme rótulo.","b":["Tempero picante e aromático para carnes","Dispensa molhos prontos","Rende bastante"],"u":"Hidrate com azeite e vinagre; ajuste a quantidade ao gosto.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/557.jpg","id":"557"},
    {"c":"395","n":"Chimichurri sem Pimenta","cat":"Temperos","d":"Chimichurri tradicional de ervas desidratadas, sem pimenta. Composição conforme rótulo.","b":["Sabor suave, bom para toda a família","Ervas como salsa e orégano em um só tempero","Carnes, pães, legumes e saladas"],"u":"Hidrate com azeite e um fio de vinagre.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/395.jpg","id":"395"},
    {"c":"1406","n":"Coentro em Grão","cat":"Temperos","d":"Sementes inteiras de coentro (Coriandrum sativum). Aroma cítrico e floral, diferente da folha.","b":["Tempero clássico de conservas, curries e carnes","Mais aroma quando levemente tostado e moído na hora","Uso culinário tradicional como digestivo"],"u":"Toste por 1 min na frigideira seca e moa antes de usar.","f":["taco"],"a":null,"tag":null,"img":"fotos/1406.jpg","id":"1406"},
    {"c":"396","n":"Colorau (Coloral)","cat":"Temperos","d":"Tempero em pó feito de urucum (Bixa orellana), usado para dar cor avermelhada aos pratos.","b":["Corante natural à base de urucum","Cor e sabor suave em carnes, arroz e moquecas","Tradição da culinária brasileira"],"u":"1 colher (chá) no refogado já colore bem.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/396.jpg","id":"396"},
    {"c":"123","n":"Cominho em Pó","cat":"Temperos","d":"Sementes de cominho (Cuminum cyminum) moídas. Sabor marcante, quente e levemente amargo.","b":["Essencial em feijão, carnes, homus e pratos nordestinos","Pequenas quantidades trazem muito sabor","Uso culinário tradicional como digestivo"],"u":"Comece com 1/2 colher (chá); o sabor é intenso.","f":["taco"],"a":null,"tag":null,"img":"fotos/123.jpg","id":"123"},
    {"c":"589","n":"Creme de Cebola em Pó","cat":"Temperos","d":"Mistura em pó sabor cebola para molhos, patês e sopas. Composição conforme rótulo.","b":["Base rápida para patês e molhos cremosos","Tempera batatas, frango e sopas","Prático para receitas de última hora"],"u":"Misture com creme de leite ou iogurte para patê. Atenção ao sódio.","f":["rotulo","oms_sal"],"a":null,"tag":null,"img":"fotos/589.jpg","id":"589"},
    {"c":"594","n":"Curry","cat":"Temperos","d":"Mistura de especiarias de origem indiana, com cúrcuma, coentro, cominho, feno-grego e pimentas.","b":["Combina várias especiarias num só tempero","Sabor quente para frango, legumes, lentilha e arroz","Contém cúrcuma, fonte de curcuminoides"],"u":"Refogue o curry no óleo por 30 s antes de adicionar os ingredientes.","f":["rotulo","nccih_turmeric"],"a":null,"tag":null,"img":"fotos/594.jpg","id":"594"},
    {"c":"898","n":"Flor de Sal","cat":"Temperos","d":"Cristais finos que se formam na superfície das salinas e são colhidos à mão. Textura delicada e crocante.","b":["Sal de finalização: pouca quantidade, muito sabor","Crocância sobre carnes, saladas e doces","Valoriza o prato pronto"],"u":"Use no final, sobre o prato montado. Ainda é sal: consumo moderado.","f":["oms_sal"],"a":null,"tag":null,"img":"","id":"898"},
    {"c":"397","n":"Fumaça em Pó","cat":"Temperos","d":"Aromatizante em pó com sabor defumado. Composição conforme rótulo.","b":["Sabor de defumado sem defumador","Feijão, caldos, carnes e molhos","Poucas pitadas bastam"],"u":"Use pouco: 1 pitada por porção.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/397.jpg","id":"397"},
    {"c":"766","n":"Lemon e Ervas Finas","cat":"Temperos","d":"Mistura de raspas cítricas desidratadas e ervas finas. Composição conforme rótulo.","b":["Frescor para peixes, frango e legumes","Ervas aromáticas em um só tempero","Ajuda a usar menos sal"],"u":"Tempere antes de assar ou grelhar.","f":["rotulo","guia"],"a":null,"tag":null,"img":"fotos/766.jpg","id":"766"},
    {"c":"398","n":"Lemon Pepper","cat":"Temperos","d":"Tempero de pimenta-do-reino com raspas de limão desidratadas. Composição conforme rótulo.","b":["Cítrico e picante na medida","Clássico para frango, peixes e saladas","Ajuda a usar menos sal"],"u":"Polvilhe antes de grelhar ou assar.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/398.jpg","id":"398"},
    {"c":"561","n":"Manjericão Seco","cat":"Temperos","d":"Folhas de manjericão (Ocimum basilicum) desidratadas.","b":["Aroma clássico em molhos de tomate, massas e pizzas","Erva aromática: sabor sem precisar de mais sal","Longa durabilidade"],"u":"Adicione no final do cozimento para preservar o aroma.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/561.jpg","id":"561"},
    {"c":"511","n":"Manjerona Desidratada","cat":"Temperos","d":"Folhas secas de manjerona (Origanum majorana). Sabor mais suave e adocicado que o orégano.","b":["Ótima em carnes, sopas, recheios e ovos","Erva aromática que reduz a necessidade de sal","Uso culinário tradicional"],"u":"Esfregue as folhas nas mãos antes de usar para liberar o aroma.","f":["guia"],"a":null,"tag":null,"img":"fotos/511.jpg","id":"511"},
    {"c":"586","n":"Mostarda Moída","cat":"Temperos","d":"Sementes de mostarda moídas. Base para mostarda caseira e marinadas.","b":["Sabor picante e aromático","Base para molho de mostarda caseiro","Tempera carnes, molhos e vinagretes"],"u":"Misture com água fria, vinagre e sal para fazer mostarda caseira.","f":["taco"],"a":null,"tag":null,"img":"fotos/586.jpg","id":"586"},
    {"c":"476","n":"Noz-Moscada em Bola","cat":"Temperos","d":"Semente inteira de noz-moscada (Myristica fragrans). Rale na hora para máximo aroma.","b":["Aroma mais intenso quando ralada na hora","Clássica em molho branco, purês e doces","Dura muito tempo inteira"],"u":"Use pouquíssimo: uma pitada basta. Em grandes quantidades não é segura.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/476.jpg","id":"476"},
    {"c":"563","n":"Noz-Moscada Moída","cat":"Temperos","d":"Noz-moscada (Myristica fragrans) já moída.","b":["Praticidade para molho branco, purês e bolos","Aroma quente e adocicado","Pequena quantidade rende muito"],"u":"Uma pitada por receita. Em grandes quantidades não é segura.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/563.jpg","id":"563"},
    {"c":"1134","n":"Orange Pepper","cat":"Temperos","d":"Tempero de pimenta com raspas de laranja desidratadas. Composição conforme rótulo.","b":["Cítrico adocicado para frango, peixes e porco","Alternativa ao lemon pepper","Ajuda a usar menos sal"],"u":"Tempere antes de assar ou grelhar.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1134.jpg","id":"1134"},
    {"c":"614","n":"Orégano","cat":"Temperos","d":"Folhas desidratadas de orégano (Origanum vulgare).","b":["Clássico em pizzas, molhos e saladas","Erva aromática que reduz a necessidade de sal","Longa durabilidade"],"u":"Adicione no final do preparo ou direto sobre a pizza.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/614.jpg","id":"614"},
    {"c":"424","n":"Páprica Defumada","cat":"Temperos","d":"Pimentão vermelho seco, defumado e moído.","b":["Sabor defumado e cor intensa","Carnes, batatas, feijão e ovos","Sem ardência"],"u":"Não queime no óleo quente: adicione no fim do refogado.","f":["taco"],"a":null,"tag":null,"img":"fotos/424.jpg","id":"424"},
    {"c":"407","n":"Páprica Doce","cat":"Temperos","d":"Pimentão vermelho seco e moído, de sabor suave e adocicado.","b":["Cor e sabor suave sem ardência","Frango, legumes, molhos e ovos","Ótima para crianças"],"u":"Adicione no fim do refogado para não amargar.","f":["taco"],"a":null,"tag":null,"img":"fotos/407.jpg","id":"407"},
    {"c":"512","n":"Páprica Picante","cat":"Temperos","d":"Pimentão vermelho e pimentas secas moídos, com ardência moderada.","b":["Cor, sabor e ardência na medida","Carnes, molhos e petiscos","Substitui a pimenta em pó comum"],"u":"Ajuste a quantidade ao gosto.","f":["taco"],"a":null,"tag":null,"img":"fotos/512.jpg","id":"512"},
    {"c":"521","n":"Pimenta Calabresa em Flocos","cat":"Temperos","d":"Pimenta vermelha seca em flocos, com sementes.","b":["Ardência para pizzas, massas e molhos","Contém capsaicina, responsável pela ardência","Rende muito"],"u":"Uma pitada por porção; aumente aos poucos.","f":["taco"],"a":null,"tag":null,"img":"fotos/521.jpg","id":"521"},
    {"c":"533","n":"Pimenta-do-Reino em Pó","cat":"Temperos","d":"Pimenta preta (Piper nigrum) moída. Contém piperina, que dá a ardência.","b":["Tempero básico de quase todas as receitas","A piperina aumenta a absorção da curcumina da cúrcuma","Ardência suave e aroma quente"],"u":"Use no final para mais aroma.","f":["taco","nccih_turmeric"],"a":null,"tag":null,"img":"fotos/533.jpg","id":"533"},
    {"c":"478","n":"Pimenta Preta em Grãos","cat":"Temperos","d":"Grãos inteiros de pimenta-do-reino (Piper nigrum).","b":["Mais aroma quando moída na hora","Ideal para moedores, conservas e caldos","Dura muito tempo"],"u":"Moa na hora ou use inteira em caldos e conservas.","f":["taco"],"a":null,"tag":null,"img":"fotos/478.jpg","id":"478"},
    {"c":"14","n":"Pimenta Síria em Pó","cat":"Temperos","d":"Mistura árabe de especiarias como pimenta-da-jamaica, canela, cravo e pimenta-do-reino. Composição conforme rótulo.","b":["Tempero típico de quibe, esfiha e kafta","Aroma quente e adocicado","Várias especiarias em um só tempero"],"u":"1 colher (chá) para cada 500 g de carne.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/14.jpg","id":"14"},
    {"c":"479","n":"Sal de Parrilla","cat":"Temperos","d":"Sal grosso de granulação média, próprio para carnes na grelha.","b":["Granulação que adere bem à carne","Tempera sem desmanchar rápido","Ideal para churrasco"],"u":"Aplique pouco antes de levar à grelha. Consumo moderado.","f":["oms_sal"],"a":null,"tag":null,"img":"fotos/479.jpg","id":"479"},
    {"c":"484","n":"Sal Rosa do Himalaia Grosso","cat":"Temperos","d":"Sal-gema de cor rosada, extraído de minas no Paquistão. Cor vem de traços de ferro e outros minerais.","b":["Sabor suave, ideal para moedores e churrasco","Menos processado que o sal refinado","Ainda é sal: a OMS recomenda menos de 5 g por dia"],"u":"Use em moedor ou em carnes.","f":["oms_sal"],"a":"O teor de minerais é pequeno; não substitui fontes de iodo. O sal refinado brasileiro é iodado.","tag":null,"img":"fotos/484.jpg","id":"484"},
    {"c":"1029","n":"Sal Marinho Integral","cat":"Temperos","d":"Sal de evaporação da água do mar, sem refino.","b":["Menos processado que o sal refinado","Sabor mais suave","Ainda é sal: a OMS recomenda menos de 5 g por dia"],"u":"Use como sal comum, com moderação.","f":["oms_sal"],"a":"Pode não ser iodado. Inclua outras fontes de iodo na alimentação.","tag":null,"img":"fotos/1029.jpg","id":"1029"},
    {"c":"597","n":"Sal Rosa do Himalaia Fino","cat":"Temperos","d":"Sal-gema rosado moído fino, para uso diário.","b":["Dissolve fácil em qualquer preparo","Menos processado que o sal refinado","Ainda é sal: a OMS recomenda menos de 5 g por dia"],"u":"Use como sal comum, com moderação.","f":["oms_sal"],"a":"O teor de minerais é pequeno; não substitui fontes de iodo.","tag":null,"img":"fotos/597.jpg","id":"597"},
    {"c":"874","n":"Tempero Gaúcho","cat":"Temperos","d":"Mistura de sal e especiarias para carnes no estilo churrasco gaúcho. Composição conforme rótulo.","b":["Tempera carnes em uma única etapa","Sabor de churrasco tradicional","Prático"],"u":"Tempere a carne antes de assar. Contém sal.","f":["rotulo","oms_sal"],"a":null,"tag":null,"img":"","id":"874"},
    {"c":"875","n":"Tempero Mineiro","cat":"Temperos","d":"Mistura de especiarias no estilo da cozinha mineira, para feijão, carnes e legumes. Composição conforme rótulo.","b":["Sabor caseiro em um só tempero","Feijão, frango, carne de porco e couve","Prático"],"u":"Use no refogado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/875.jpg","id":"875"},
    {"c":"755","n":"Tempera Tudo","cat":"Temperos","d":"Mistura versátil de especiarias e ervas para o dia a dia. Composição conforme rótulo.","b":["Um tempero para carnes, legumes, arroz e ovos","Substitui vários potes na cozinha","Prático"],"u":"Comece com 1 colher (chá) por porção.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/755.jpg","id":"755"},
    {"c":"410","n":"Tempero Ana Maria","cat":"Temperos","d":"Mistura de ervas e especiarias da linha a granel. Composição conforme rótulo do fornecedor.","b":["Tempero completo para o dia a dia","Carnes, frango, legumes e arroz","Prático"],"u":"Use no refogado ou para temperar carnes.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/410.jpg","id":"410"},
    {"c":"365","n":"Tempero Baiano","cat":"Temperos","d":"Mistura clássica de especiarias como cominho, pimenta, açafrão e orégano. Composição conforme rótulo.","b":["Sabor intenso para feijão, carnes e frutos do mar","Várias especiarias em um só tempero","Tradição brasileira"],"u":"1 colher (chá) no refogado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/365.jpg","id":"365"},
    {"c":"1158","n":"Tempero Baiano sem Pimenta","cat":"Temperos","d":"Versão suave do tempero baiano, sem pimenta. Composição conforme rótulo.","b":["Todo o sabor do baiano sem ardência","Bom para toda a família","Feijão, frango e legumes"],"u":"1 colher (chá) no refogado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1158.jpg","id":"1158"},
    {"c":"434","n":"Tempero do Chef","cat":"Temperos","d":"Mistura de ervas e especiarias para carnes e legumes. Composição conforme rótulo.","b":["Tempero completo em um só pote","Carnes, legumes e batatas","Prático"],"u":"Tempere antes de assar ou grelhar.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/434.jpg","id":"434"},
    {"c":"409","n":"Tempero Edu Guedes","cat":"Temperos","d":"Mistura de ervas e especiarias da linha a granel. Composição conforme rótulo do fornecedor.","b":["Tempero completo para o dia a dia","Carnes, frango e legumes","Prático"],"u":"Use no refogado ou para temperar carnes.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/409.jpg","id":"409"},
    {"c":"1850","n":"Tempero para Arroz","cat":"Temperos","d":"Mistura de especiarias e ervas para arroz. Composição conforme rótulo.","b":["Arroz mais saboroso e colorido","Dispensa caldos em tablete","Prático"],"u":"1 colher (chá) por xícara de arroz, no refogado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1850.jpg","id":"1850"},
    {"c":"754","n":"Tempero para Feijão","cat":"Temperos","d":"Mistura de especiarias para feijão. Composição conforme rótulo.","b":["Feijão com sabor caseiro","Especiarias como cominho, louro e alho em um só tempero","Prático"],"u":"1 colher (chá) no refogado do feijão.","f":["rotulo"],"a":null,"tag":null,"img":"","id":"754"},
    {"c":"413","n":"Tempero Pega Marido","cat":"Temperos","d":"Mistura de ervas e especiarias da linha a granel. Composição conforme rótulo do fornecedor.","b":["Tempero completo para carnes e frango","Sabor marcante","Prático"],"u":"Tempere a carne antes do preparo.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/413.jpg","id":"413"},
    {"c":"415","n":"Tempero Alho, Cebola e Salsa","cat":"Temperos","d":"Mistura desidratada de alho, cebola e salsa.","b":["O trio básico da cozinha pronto para usar","Arroz, feijão, carnes e sopas","Economiza tempo no preparo"],"u":"Use no refogado, 1 colher (chá) por porção.","f":["guia"],"a":null,"tag":null,"img":"fotos/415.jpg","id":"415"},
    {"c":"425","n":"Vinagrete em Flocos","cat":"Temperos","d":"Mistura desidratada de legumes e temperos para vinagrete. Composição conforme rótulo.","b":["Vinagrete pronto em minutos","Basta hidratar com vinagre e azeite","Acompanha churrasco e saladas"],"u":"Hidrate com vinagre, água e azeite por 15 min.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/425.jpg","id":"425"},
    {"c":"535","n":"Aveia em Flocos","cat":"Farinhas, Sementes e Pós","d":"Grão integral de aveia laminado. Fonte de fibras, incluindo a beta-glucana.","b":["A beta-glucana da aveia ajuda a manter o colesterol em níveis normais com 3 g por dia, cerca de 70 g de aveia (alegação aprovada na UE)","Saciedade e energia de liberação lenta","Mingau, overnight oats, vitaminas e receitas"],"u":"2 a 3 colheres (sopa) ao dia no café da manhã.","f":["efsa","taco"],"a":null,"tag":null,"img":"fotos/535.jpg","id":"535"},
    {"c":"757","n":"Amido de Milho","cat":"Farinhas, Sementes e Pós","d":"Amido extraído do milho, pó fino e neutro.","b":["Engrossa molhos, cremes e mingaus","Deixa bolos e biscoitos mais leves","Naturalmente sem glúten"],"u":"Dissolva em líquido frio antes de levar ao fogo.","f":["taco"],"a":null,"tag":null,"img":"fotos/757.jpg","id":"757"},
    {"c":"591","n":"Açúcar de Coco","cat":"Farinhas, Sementes e Pós","d":"Seiva da flor do coqueiro evaporada e cristalizada. Sabor que lembra caramelo.","b":["Menos refinado que o açúcar branco","Sabor caramelizado em cafés e receitas","Substitui o açúcar na mesma medida"],"u":"Use na mesma proporção do açúcar comum. Ainda é açúcar: consumo moderado.","f":["guia"],"a":null,"tag":null,"img":"fotos/591.jpg","id":"591"},
    {"c":"558","n":"Açúcar Demerara","cat":"Farinhas, Sementes e Pós","d":"Açúcar de cana com refino leve, grãos dourados e sabor suave.","b":["Menos processado que o açúcar refinado","Sabor suave, não altera receitas","Dissolve bem"],"u":"Substitui o açúcar branco na mesma medida. Consumo moderado.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/558.jpg","id":"558"},
    {"c":"385","n":"Açúcar Mascavo","cat":"Farinhas, Sementes e Pós","d":"Açúcar de cana sem refino, úmido e escuro, com sabor intenso de melaço.","b":["Não passa por refino: preserva o melaço","Sabor marcante em bolos, granolas e biscoitos","Contém pequenas quantidades de minerais da cana"],"u":"Use em receitas; ainda é açúcar, então com moderação.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/385.jpg","id":"385"},
    {"c":"450","n":"Argila Branca","cat":"Farinhas, Sementes e Pós","d":"Argila caulim, a mais suave das argilas cosméticas.","b":["Indicada para peles sensíveis e secas","Ajuda a remover impurezas sem ressecar","Textura fina e suave"],"u":"Misture com água até formar pasta, aplique no rosto por 10 a 15 min e enxágue.","f":["rotulo"],"a":"Uso externo. Não ingerir.","tag":"Uso externo","img":"","id":"450","sw":"#fefefe"},
    {"c":"724","n":"Argila Cinza","cat":"Farinhas, Sementes e Pós","d":"Argila cosmética rica em minerais, de ação purificante.","b":["Indicada para peles oleosas","Ajuda a controlar a oleosidade","Máscaras faciais e capilares"],"u":"Misture com água, aplique por 10 a 15 min e enxágue.","f":["rotulo"],"a":"Uso externo. Não ingerir.","tag":"Uso externo","img":"","id":"724","sw":"#a9a7aa"},
    {"c":"489","n":"Argila Marrom","cat":"Farinhas, Sementes e Pós","d":"Argila cosmética rica em ferro e outros minerais.","b":["Tradicionalmente usada em máscaras para pele e cabelos","Ajuda na limpeza profunda","Máscaras faciais e corporais"],"u":"Misture com água, aplique por 10 a 15 min e enxágue.","f":["rotulo"],"a":"Uso externo. Não ingerir.","tag":"Uso externo","img":"","id":"489","sw":"#894b00"},
    {"c":"449","n":"Argila Preta","cat":"Farinhas, Sementes e Pós","d":"Argila cosmética escura, rica em minerais e matéria orgânica.","b":["Usada em máscaras de limpeza profunda","Indicada para peles oleosas","Também usada em máscaras capilares"],"u":"Misture com água, aplique por 10 a 15 min e enxágue.","f":["rotulo"],"a":"Uso externo. Não ingerir.","tag":"Uso externo","img":"","id":"449","sw":"#010101"},
    {"c":"487","n":"Argila Rosa","cat":"Farinhas, Sementes e Pós","d":"Mistura de argila branca e vermelha, de ação suave.","b":["Indicada para peles sensíveis","Limpeza suave com toque de viço","Máscaras faciais"],"u":"Misture com água, aplique por 10 a 15 min e enxágue.","f":["rotulo"],"a":"Uso externo. Não ingerir.","tag":"Uso externo","img":"","id":"487","sw":"#fbc4db"},
    {"c":"486","n":"Argila Verde","cat":"Farinhas, Sementes e Pós","d":"A argila mais usada em cosmética, de ação adstringente.","b":["Tradicionalmente usada em máscaras para pele oleosa","Ajuda a controlar a oleosidade","Máscaras faciais e capilares"],"u":"Misture com água, aplique por 10 a 15 min e enxágue.","f":["rotulo"],"a":"Uso externo. Não ingerir.","tag":"Uso externo","img":"","id":"486","sw":"#43852d"},
    {"c":"488","n":"Argila Vermelha","cat":"Farinhas, Sementes e Pós","d":"Argila cosmética rica em óxido de ferro.","b":["Tradicionalmente usada em máscaras faciais e corporais","Cor avermelhada natural","Pode ser misturada a outras argilas"],"u":"Misture com água, aplique por 10 a 15 min e enxágue.","f":["rotulo"],"a":"Uso externo. Não ingerir.","tag":"Uso externo","img":"","id":"488","sw":"#b40001"},
    {"c":"523","n":"Cacau em Pó 100%","cat":"Farinhas, Sementes e Pós","d":"Cacau em pó puro, sem açúcar e sem leite.","b":["Fonte de flavanóis do cacau","Rico em fibras e minerais como magnésio e ferro","Sabor intenso de chocolate sem açúcar"],"u":"1 colher (sopa) em vitaminas, mingaus, bolos e bebidas.","f":["taco","efsa"],"a":null,"tag":null,"img":"fotos/523.jpg","id":"523"},
    {"c":"1790","n":"Cacau em Pó Black 100%","cat":"Farinhas, Sementes e Pós","d":"Cacau em pó alcalinizado de cor escura intensa, sem açúcar.","b":["Cor preta e sabor intenso para bolos e biscoitos","Sem açúcar","Dissolve fácil em bebidas"],"u":"Use como o cacau comum; a cor escurece mais.","f":["taco"],"a":null,"tag":null,"img":"fotos/1790.jpg","id":"1790"},
    {"c":"392","n":"Canela em Pó","cat":"Farinhas, Sementes e Pós","d":"Casca de canela moída. Aroma doce e quente.","b":["Dá sabor adocicado sem adicionar açúcar","Clássica em frutas, mingaus, cafés e bolos","Especiaria de uso culinário tradicional"],"u":"Polvilhe 1/2 colher (chá) em frutas, mingau ou café.","f":["nccih_cinnamon"],"a":null,"tag":null,"img":"fotos/392.jpg","id":"392"},
    {"c":"75","n":"Carvão Vegetal em Pó","cat":"Farinhas, Sementes e Pós","d":"Carvão vegetal em pó bem fino. Usado na culinária como corante preto natural e em cosméticos caseiros.","b":["Cor preta natural para pães, massas, sorvetes e drinks","Na forma ativada, tem alegação aprovada na União Europeia para reduzir gases em excesso após as refeições (1 g antes e 1 g depois)","Usado em máscaras faciais e sabonetes artesanais"],"u":"Na culinária: 1/2 colher (chá) já escurece massas e cremes. Para gases, confirme com o fornecedor se o carvão é ativado e siga a orientação de um profissional.","f":["efsa_carvao","ncbi_carvao"],"a":"Pode reduzir a absorção de medicamentos e anticoncepcionais: mantenha 2 horas de intervalo. Em caso de intoxicação, procure atendimento médico: não use por conta própria.","tag":null,"img":"fotos/75.jpg","id":"75"},
    {"c":"536","n":"Catuaba em Pó","cat":"Farinhas, Sementes e Pós","d":"Casca de catuaba moída, planta nativa brasileira.","b":["Uso popular como tônico, sem comprovação científica","Planta da medicina popular brasileira","Consumida em infusões e bebidas"],"u":"Siga a orientação de um profissional de saúde.","f":["sem_mono"],"a":"Evidência científica limitada. Evite na gravidez, amamentação e com uso de medicamentos.","tag":null,"img":"fotos/536.jpg","id":"536"},
    {"c":"163","n":"Dolomita em Pó","cat":"Farinhas, Sementes e Pós","d":"Mineral natural fonte de carbonato de cálcio e magnésio.","b":["Fonte de cálcio e magnésio","Suplementos de cálcio e magnésio devem ser usados com orientação profissional","Também usada no cultivo de plantas"],"u":"Use somente com orientação de nutricionista ou médico.","f":["ods_ca","ods_mg"],"a":"Pode conter traços de metais pesados. Não use sem orientação profissional.","tag":null,"img":"fotos/163.jpg","id":"163"},
    {"c":"443","n":"Chia","cat":"Farinhas, Sementes e Pós","d":"Sementes de Salvia hispanica. Formam gel quando hidratadas.","b":["Rica em fibras, que ajudam o intestino","Fonte de ômega-3 vegetal (ALA)","Gel que dá saciedade e substitui ovo em receitas"],"u":"1 colher (sopa) ao dia, hidratada em água, iogurte ou suco. Beba bastante água.","f":["taco","efsa"],"a":null,"tag":null,"img":"fotos/443.jpg","id":"443"},
    {"c":"896","n":"Eritritol Cristal","cat":"Farinhas, Sementes e Pós","d":"Adoçante natural do tipo poliol, obtido por fermentação. Cerca de 70% do dulçor do açúcar.","b":["Praticamente sem calorias","Não eleva a glicemia","Não causa cáries"],"u":"Substitui o açúcar em cafés, chás e receitas. Em excesso pode causar desconforto intestinal.","f":["efsa"],"a":"Use com moderação: estudos recentes investigam uma possível relação entre consumo elevado de eritritol e risco cardiovascular.","tag":null,"img":"fotos/896.jpg","id":"896"},
    {"c":"445","n":"Farelo de Aveia","cat":"Farinhas, Sementes e Pós","d":"Camada externa do grão de aveia, a parte mais rica em beta-glucana.","b":["Mais concentrado em beta-glucana que a aveia em flocos","A beta-glucana ajuda a manter o colesterol normal (alegação aprovada na UE)","Saciedade e regularidade intestinal"],"u":"1 a 2 colheres (sopa) em frutas, iogurte ou receitas.","f":["efsa","taco"],"a":null,"tag":null,"img":"fotos/445.jpg","id":"445"},
    {"c":"539","n":"Farinha de Amêndoa","cat":"Farinhas, Sementes e Pós","d":"Amêndoas moídas bem finas.","b":["Sem glúten e com poucos carboidratos","Fonte de gorduras boas, vitamina E e proteínas","Bolos, biscoitos e empanados"],"u":"Substitui parte da farinha de trigo em receitas.","f":["taco","efsa"],"a":null,"tag":null,"img":"fotos/539.jpg","id":"539"},
    {"c":"470","n":"Farinha de Arroz","cat":"Farinhas, Sementes e Pós","d":"Arroz moído fino. Neutra e sem glúten.","b":["Naturalmente sem glúten","Base para pães, bolos e empanados sem trigo","Sabor neutro"],"u":"Combine com fécula e polvilho em receitas sem glúten.","f":["taco"],"a":"Pode haver contaminação cruzada com glúten na loja.","tag":null,"img":"fotos/470.jpg","id":"470"},
    {"c":"431","n":"Farinha de Aveia","cat":"Farinhas, Sementes e Pós","d":"Aveia moída fina, com todo o grão.","b":["Fonte de fibras e beta-glucana","Substitui parte da farinha de trigo","Mingaus, panquecas e bolos"],"u":"Substitua até metade da farinha de trigo nas receitas.","f":["efsa","taco"],"a":null,"tag":null,"img":"fotos/431.jpg","id":"431"},
    {"c":"548","n":"Farinha de Banana Verde","cat":"Farinhas, Sementes e Pós","d":"Banana verde seca e moída. Rica em amido resistente, um tipo de fibra.","b":["Rica em amido resistente, que funciona como fibra no intestino (Embrapa)","Contribui para a saciedade","Sem glúten"],"u":"1 a 2 colheres (sopa) ao dia em sucos, vitaminas e receitas frias.","f":["embrapa_bv"],"a":null,"tag":null,"img":"fotos/548.jpg","id":"548"},
    {"c":"506","n":"Farinha de Berinjela","cat":"Farinhas, Sementes e Pós","d":"Berinjela desidratada e moída.","b":["Fonte de fibras","Contribui para a saciedade","Fácil de adicionar em sucos e sopas"],"u":"1 colher (sopa) ao dia em sucos, iogurtes ou sopas.","f":["taco"],"a":null,"tag":null,"img":"fotos/506.jpg","id":"506"},
    {"c":"1026","n":"Farinha de Beterraba","cat":"Farinhas, Sementes e Pós","d":"Beterraba desidratada e moída.","b":["Cor vermelha natural para massas, pães e bolos","Fonte de nitratos da beterraba","Fonte de fibras"],"u":"1 colher (sopa) em vitaminas, sucos e massas.","f":["taco"],"a":null,"tag":null,"img":"fotos/1026.jpg","id":"1026"},
    {"c":"1675","n":"Farinha de Chia","cat":"Farinhas, Sementes e Pós","d":"Semente de chia moída.","b":["Fibras e ômega-3 vegetal (ALA)","Mais fácil de misturar que a semente inteira","Enriquece pães, bolos e vitaminas"],"u":"1 colher (sopa) ao dia. Guarde em pote bem fechado.","f":["taco","efsa"],"a":null,"tag":null,"img":"fotos/1675.jpg","id":"1675"},
    {"c":"223","n":"Farinha de Coco","cat":"Farinhas, Sementes e Pós","d":"Polpa de coco seca, desengordurada e moída.","b":["Muito rica em fibras","Sem glúten e com poucos carboidratos","Sabor suave de coco em bolos e panquecas"],"u":"Absorve muito líquido: use menos que a farinha de trigo.","f":["taco"],"a":null,"tag":null,"img":"fotos/223.jpg","id":"223"},
    {"c":"224","n":"Farinha de Gengibre","cat":"Farinhas, Sementes e Pós","d":"Gengibre seco moído. Sabor picante e quente.","b":["Uso reconhecido pela ANVISA como auxiliar contra enjoo de movimento","Sabor em chás, sucos, biscoitos e molhos","Especiaria de uso tradicional"],"u":"1/4 a 1/2 colher (chá) em chás, sucos ou receitas.","f":["ff","nccih_ginger"],"a":"Consulte o médico se usa anticoagulantes.","tag":null,"img":"fotos/224.jpg","id":"224"},
    {"c":"1157","n":"Farinha de Grão-de-Bico","cat":"Farinhas, Sementes e Pós","d":"Grão-de-bico cru moído.","b":["Fonte de proteína vegetal e fibras","Sem glúten","Omeletes veganas, panquecas, falafel e pães"],"u":"Misture com água e temperos para omelete sem ovo.","f":["taco"],"a":null,"tag":null,"img":"fotos/1157.jpg","id":"1157"},
    {"c":"577","n":"Farinha de Linhaça Dourada","cat":"Farinhas, Sementes e Pós","d":"Linhaça dourada moída. Moída, os nutrientes são melhor aproveitados.","b":["Fonte de ômega-3 vegetal (ALA) e fibras","Ajuda no funcionamento intestinal","Contém lignanas"],"u":"1 colher (sopa) ao dia. Guarde na geladeira após aberta.","f":["nccih_flax","taco"],"a":null,"tag":null,"img":"fotos/577.jpg","id":"577"},
    {"c":"600","n":"Farinha de Maracujá","cat":"Farinhas, Sementes e Pós","d":"Casca de maracujá seca e moída. Rica em pectina, uma fibra solúvel.","b":["Rica em fibras solúveis (pectina)","Contribui para a saciedade","Aproveita a casca da fruta"],"u":"1 colher (sopa) ao dia em sucos, iogurtes ou vitaminas.","f":["taco"],"a":null,"tag":null,"img":"fotos/600.jpg","id":"600"},
    {"c":"549","n":"Farinha Panko","cat":"Farinhas, Sementes e Pós","d":"Farinha de pão de estilo japonês, em flocos grandes.","b":["Empanados mais sequinhos e crocantes","Textura mais aerada que a farinha de rosca comum","Ótima para airfryer e forno"],"u":"Passe o alimento no ovo e depois no panko.","f":["rotulo"],"a":"Contém glúten.","tag":null,"img":"fotos/549.jpg","id":"549"},
    {"c":"1702","n":"Farinha de Semente de Abóbora Crua","cat":"Farinhas, Sementes e Pós","d":"Semente de abóbora crua moída.","b":["Fonte de proteínas, magnésio e zinco","Sem glúten","Enriquece vitaminas, pães e mingaus"],"u":"1 a 2 colheres (sopa) ao dia.","f":["taco"],"a":null,"tag":null,"img":"fotos/1702.jpg","id":"1702"},
    {"c":"748","n":"Farinha de Uva","cat":"Farinhas, Sementes e Pós","d":"Casca e semente de uva secas e moídas.","b":["Fonte de fibras","Contém polifenóis da uva","Enriquece sucos, iogurtes e receitas"],"u":"1 colher (sopa) ao dia.","f":["taco"],"a":null,"tag":null,"img":"fotos/748.jpg","id":"748"},
    {"c":"897","n":"Fécula de Batata","cat":"Farinhas, Sementes e Pós","d":"Amido extraído da batata.","b":["Sem glúten","Deixa massas leves e macias","Engrossa molhos e cremes"],"u":"Combine com outras farinhas sem glúten.","f":["taco"],"a":null,"tag":null,"img":"fotos/897.jpg","id":"897"},
    {"c":"572","n":"Feno-Grego em Pó","cat":"Farinhas, Sementes e Pós","d":"Sementes de feno-grego (Trigonella foenum-graecum) moídas. Sabor que lembra xarope de bordo.","b":["Especiaria usada em curries e temperos indianos","Fonte de fibras","Uso tradicional como digestivo"],"u":"1/2 colher (chá) em curries, pães e caldos.","f":["nccih_fenugreek"],"a":"Evite na gravidez. Consulte o médico se usa medicamentos para diabetes.","tag":null,"img":"fotos/572.jpg","id":"572"},
    {"c":"543","n":"Fibra de Maçã","cat":"Farinhas, Sementes e Pós","d":"Maçã seca e moída. Rica em pectina, uma fibra solúvel.","b":["Fonte de fibras solúveis","Contribui para a saciedade","Sabor suave em sucos e iogurtes"],"u":"1 colher (sopa) ao dia com bastante água.","f":["taco"],"a":null,"tag":null,"img":"fotos/543.jpg","id":"543"},
    {"c":"420","n":"Gengibre em Pó","cat":"Farinhas, Sementes e Pós","d":"Raiz de gengibre (Zingiber officinale) seca e moída.","b":["Uso reconhecido pela ANVISA como auxiliar contra enjoo de movimento","Tempero para chás, sucos, carnes e doces","Sabor picante e aquecido"],"u":"1/4 a 1/2 colher (chá) em chás, sucos ou receitas.","f":["ff","nccih_ginger"],"a":"Consulte o médico se usa anticoagulantes.","tag":null,"img":"","id":"420"},
    {"c":"540","n":"Gergelim Branco","cat":"Farinhas, Sementes e Pós","d":"Sementes de gergelim descascadas.","b":["Fonte de cálcio, gorduras boas e fibras","Base para tahine caseiro","Finaliza pães, saladas e pratos orientais"],"u":"Toste levemente para realçar o sabor.","f":["taco"],"a":null,"tag":null,"img":"fotos/540.jpg","id":"540"},
    {"c":"585","n":"Gergelim Preto","cat":"Farinhas, Sementes e Pós","d":"Sementes de gergelim com casca, de sabor mais intenso.","b":["Fonte de cálcio, ferro e fibras","Contraste de cor em pratos e pães","Sabor mais marcante que o branco"],"u":"Use em saladas, arroz, pães e sushi.","f":["taco"],"a":null,"tag":null,"img":"fotos/585.jpg","id":"585"},
    {"c":"522","n":"Gérmen de Trigo","cat":"Farinhas, Sementes e Pós","d":"Embrião do grão de trigo, a parte mais nutritiva do grão.","b":["Fonte de vitamina E e vitaminas do complexo B","Fonte de proteínas e fibras","Enriquece iogurtes, vitaminas e pães"],"u":"1 colher (sopa) ao dia. Guarde na geladeira após aberto.","f":["taco"],"a":"Contém glúten.","tag":null,"img":"fotos/522.jpg","id":"522"},
    {"c":"541","n":"Ginseng em Pó","cat":"Farinhas, Sementes e Pós","d":"Raiz de ginseng seca e moída.","b":["Uso tradicional como tônico contra o cansaço","Uma das plantas mais estudadas, com resultados ainda inconclusivos","Pode ser usado em chás e vitaminas"],"u":"Siga a orientação de um profissional de saúde.","f":["nccih_ginseng"],"a":"Evite na gravidez, com anticoagulantes e medicamentos para diabetes. Não use por longos períodos sem orientação.","tag":null,"img":"fotos/541.jpg","id":"541"},
    {"c":"1751","n":"Glucomanan em Pó","cat":"Farinhas, Sementes e Pós","d":"Fibra solúvel extraída da raiz de konjac. Absorve muita água e forma gel.","b":["Contribui para a saciedade (alegação aprovada na UE para perda de peso em dieta com restrição calórica, 3 g/dia)","Ajuda a manter o colesterol normal (4 g/dia)","Fibra solúvel de alta viscosidade"],"u":"1 g antes das refeições, com 1 a 2 copos de água.","f":["efsa"],"a":"Sempre tome com bastante água para evitar engasgo. Não indicado para quem tem dificuldade de engolir.","tag":null,"img":"fotos/1751.jpg","id":"1751"},
    {"c":"903","n":"Goma Xantana","cat":"Farinhas, Sementes e Pós","d":"Espessante natural obtido por fermentação.","b":["Dá liga e elasticidade a massas sem glúten","Estabiliza molhos, sorvetes e cremes","Pouquíssima quantidade basta"],"u":"1/2 colher (chá) por xícara de farinha sem glúten.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/903.jpg","id":"903"},
    {"c":"472","n":"Grão-de-Bico","cat":"Farinhas, Sementes e Pós","d":"Leguminosa em grão, seca.","b":["Fonte de proteína vegetal e fibras","Base para homus, saladas, falafel e ensopados","Contém ferro, folato e magnésio"],"u":"Deixe de molho 8 a 12 h, descarte a água e cozinhe.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/472.jpg","id":"472"},
    {"c":"473","n":"Guaraná em Pó","cat":"Farinhas, Sementes e Pós","d":"Semente de guaraná (Paullinia cupana) torrada e moída. Fonte natural de cafeína.","b":["Uso reconhecido pela ANVISA como auxiliar contra o cansaço e a fadiga","Estimulante natural pela cafeína","Planta amazônica brasileira"],"u":"1/2 colher (chá) em sucos ou água, de preferência pela manhã.","f":["ff","efsa"],"a":"Contém cafeína. Evite à noite, na gravidez, com hipertensão ou arritmias.","tag":null,"img":"fotos/473.jpg","id":"473"},
    {"c":"595","n":"Leite de Coco em Pó Vegano","cat":"Farinhas, Sementes e Pós","d":"Leite de coco desidratado, sem ingredientes de origem animal. Composição conforme rótulo.","b":["Alternativa vegetal para receitas e bebidas","Prático: dissolve em água","Cremosidade para molhos, doces e cafés"],"u":"Dissolva em água morna na proporção do rótulo.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/595.jpg","id":"595"},
    {"c":"474","n":"Lentilha","cat":"Farinhas, Sementes e Pós","d":"Leguminosa em grão, seca.","b":["Fonte de proteína vegetal, fibras e ferro","Cozinha rápido e não precisa de molho","Sopas, saladas e hambúrgueres vegetais"],"u":"Cozinhe por 15 a 20 min em água.","f":["taco","guia"],"a":null,"tag":null,"img":"fotos/474.jpg","id":"474"},
    {"c":"460","n":"Maca Peruana em Pó","cat":"Farinhas, Sementes e Pós","d":"Raiz andina (Lepidium meyenii) seca e moída.","b":["Uso tradicional andino como alimento e fonte de disposição","Fonte de carboidratos, fibras e minerais","Sabor maltado em vitaminas e mingaus"],"u":"1 colher (chá) ao dia em vitaminas ou iogurte.","f":["msk_maca"],"a":"Evidência científica limitada. Evite na gravidez e com problemas de tireoide.","tag":null,"img":"fotos/460.jpg","id":"460"},
    {"c":"1733","n":"Maca Peruana Negra em Pó","cat":"Farinhas, Sementes e Pós","d":"Variedade escura da maca (Lepidium meyenii), seca e moída.","b":["Uso tradicional andino como alimento e fonte de disposição","Fonte de carboidratos, fibras e minerais","Sabor maltado em vitaminas"],"u":"1 colher (chá) ao dia em vitaminas ou iogurte.","f":["msk_maca"],"a":"Evidência científica limitada. Evite na gravidez e com problemas de tireoide.","tag":null,"img":"fotos/1733.jpg","id":"1733"},
    {"c":"1752","n":"Marapuama em Pó","cat":"Farinhas, Sementes e Pós","d":"Casca e raiz de marapuama (Ptychopetalum olacoides), planta amazônica, moídas.","b":["Uso popular amazônico como tônico, sem comprovação científica","Planta da medicina popular brasileira","Consumida em infusões"],"u":"Siga a orientação de um profissional de saúde.","f":["sem_mono"],"a":"Evidência científica limitada. Evite na gravidez e com uso de medicamentos.","tag":null,"img":"fotos/1752.jpg","id":"1752"},
    {"c":"475","n":"Mix de Quinoa em Grãos","cat":"Farinhas, Sementes e Pós","d":"Mistura de quinoa branca, vermelha e preta.","b":["Proteína completa, com todos os aminoácidos essenciais","Sem glúten","Substitui o arroz em saladas e acompanhamentos"],"u":"Lave bem e cozinhe por 15 min em 2 partes de água.","f":["taco"],"a":null,"tag":null,"img":"fotos/475.jpg","id":"475"},
    {"c":"15","n":"Percarbonato de Sódio","cat":"Farinhas, Sementes e Pós","d":"Alvejante à base de oxigênio para limpeza doméstica. Não é alimento.","b":["Tira manchas de roupas brancas e coloridas sem cloro","Limpa e clareia rejuntes e superfícies","Libera oxigênio na água quente"],"u":"Dissolva 1 colher (sopa) em água quente. Use luvas.","f":["rotulo"],"a":"PRODUTO DE LIMPEZA. Não ingerir. Mantenha longe de crianças e animais.","tag":"Limpeza","img":"fotos/15.jpg","id":"15"},
    {"c":"513","n":"Psyllium","cat":"Farinhas, Sementes e Pós","d":"Casca da semente de Plantago ovata. Fibra solúvel que forma gel.","b":["Ajuda a regular o intestino","Fibra solúvel que contribui para a saciedade","Dá liga a pães sem glúten"],"u":"1 colher (chá) com 1 copo grande de água. Aumente aos poucos.","f":["efsa","ff"],"a":"Tome sempre com bastante água. Afaste 2 h de medicamentos.","tag":null,"img":"fotos/513.jpg","id":"513"},
    {"c":"751","n":"Polvilho Azedo","cat":"Farinhas, Sementes e Pós","d":"Amido de mandioca fermentado.","b":["Base do pão de queijo e do biscoito de polvilho","Naturalmente sem glúten","Deixa massas aeradas e crocantes"],"u":"Escalde com líquido quente para fazer pão de queijo.","f":["taco"],"a":null,"tag":null,"img":"fotos/751.jpg","id":"751"},
    {"c":"768","n":"Polvilho Doce","cat":"Farinhas, Sementes e Pós","d":"Amido de mandioca não fermentado.","b":["Naturalmente sem glúten","Base para tapioca de liquidificador, bolos e biscoitos","Textura macia e elástica"],"u":"Use em receitas sem glúten e pão de queijo.","f":["taco"],"a":null,"tag":null,"img":"fotos/768.jpg","id":"768"},
    {"c":"485","n":"Semente de Abóbora Crua","cat":"Farinhas, Sementes e Pós","d":"Semente de abóbora sem casca, crua.","b":["Fonte de proteínas, magnésio e zinco","Lanche nutritivo e prático","Saladas, granolas e pães"],"u":"1 punhado (cerca de 30 g) ao dia.","f":["taco"],"a":null,"tag":null,"img":"fotos/485.jpg","id":"485"},
    {"c":"769","n":"Semente de Abóbora Torrada","cat":"Farinhas, Sementes e Pós","d":"Semente de abóbora torrada, pronta para consumo.","b":["Crocante e pronta para comer","Fonte de proteínas, magnésio e zinco","Petisco nutritivo"],"u":"1 punhado (cerca de 30 g) ao dia.","f":["taco"],"a":null,"tag":null,"img":"fotos/769.jpg","id":"769"},
    {"c":"565","n":"Semente de Girassol","cat":"Farinhas, Sementes e Pós","d":"Semente de girassol descascada.","b":["Fonte de vitamina E e gorduras boas","Crocância em saladas, pães e granolas","Petisco nutritivo"],"u":"1 a 2 colheres (sopa) ao dia.","f":["taco"],"a":null,"tag":null,"img":"fotos/565.jpg","id":"565"},
    {"c":"461","n":"Semente de Linhaça Dourada","cat":"Farinhas, Sementes e Pós","d":"Semente inteira de linhaça dourada.","b":["Fonte de ômega-3 vegetal (ALA) e fibras","Ajuda no funcionamento intestinal","Moída, é melhor aproveitada"],"u":"Moa na hora e use 1 colher (sopa) ao dia.","f":["nccih_flax","taco"],"a":null,"tag":null,"img":"fotos/461.jpg","id":"461"},
    {"c":"662","n":"Semente de Linhaça Marrom","cat":"Farinhas, Sementes e Pós","d":"Semente inteira de linhaça marrom.","b":["Fonte de ômega-3 vegetal (ALA) e fibras","Ajuda no funcionamento intestinal","Moída, é melhor aproveitada"],"u":"Moa na hora e use 1 colher (sopa) ao dia.","f":["nccih_flax","taco"],"a":null,"tag":null,"img":"fotos/662.jpg","id":"662"},
    {"c":"67","n":"Semente de Sucupira","cat":"Farinhas, Sementes e Pós","d":"Fruto/semente da sucupira-branca (Pterodon emarginatus), árvore do Cerrado.","b":["Uso popular no Cerrado para dores nas articulações, sem comprovação em humanos","Planta da medicina popular do Cerrado","Estudos de laboratório investigam uma possível ação anti-inflamatória"],"u":"Tradicionalmente usada em infusão ou em garrafadas. Siga orientação profissional.","f":["sem_mono"],"a":"Evidência em humanos limitada. Evite na gravidez e amamentação.","tag":null,"img":"fotos/67.jpg","id":"67","step":8,"unit":"un"},
    {"c":"566","n":"Tribulus Terrestris em Pó","cat":"Farinhas, Sementes e Pós","d":"Planta (Tribulus terrestris) seca e moída.","b":["Uso tradicional como tônico","Popular entre praticantes de atividade física","Planta de uso na medicina tradicional"],"u":"Siga a orientação de um profissional de saúde.","f":["ods_exercise"],"a":"Estudos não confirmam efeito sobre testosterona ou desempenho. Evite na gravidez e com medicamentos.","tag":null,"img":"fotos/566.jpg","id":"566"},
    {"c":"426","n":"Xilitol Cristal","cat":"Farinhas, Sementes e Pós","d":"Adoçante natural do tipo poliol, com dulçor semelhante ao açúcar.","b":["Não causa cáries e ajuda na saúde bucal (alegação aprovada na UE)","Cerca de 40% menos calorias que o açúcar","Baixo impacto na glicemia"],"u":"Substitui o açúcar na mesma medida. Em excesso pode causar desconforto intestinal.","f":["efsa"],"a":"TÓXICO PARA CÃES. Mantenha longe dos animais.","tag":null,"img":"fotos/426.jpg","id":"426"},
    {"c":"492","n":"Alecrim","cat":"Chás e Ervas","d":"Folhas secas de alecrim (Rosmarinus officinalis). Aroma resinoso e marcante.","b":["Uso reconhecido pela ANVISA como auxiliar da digestão (sensação de plenitude e gases)","Tempero clássico de carnes, batatas e pães","Chá aromático"],"u":"Chá: 1 colher (chá) em 1 xícara de água quente, abafe 10 min.","f":["ff"],"a":"Evite na gravidez e em doses altas.","tag":null,"img":"fotos/492.jpg","id":"492"},
    {"c":"493","n":"Alfazema (Lavanda)","cat":"Chás e Ervas","d":"Flores secas de Lavandula angustifolia.","b":["Estudos com lavanda indicam efeito modesto no alívio da ansiedade leve","Aroma relaxante para sachês e banhos","Chá floral e suave"],"u":"Chá: 1 colher (chá) em 1 xícara de água quente, abafe 10 min.","f":["nccih_lavender"],"a":"Evite na gravidez.","tag":null,"img":"fotos/493.jpg","id":"493"},
    {"c":"494","n":"Amora sem Espinhos (folhas)","cat":"Chás e Ervas","d":"Folhas secas da amoreira (Morus nigra).","b":["Uso popular no climatério, sem comprovação científica","Chá suave e agradável","Planta de uso tradicional brasileiro"],"u":"Chá: 1 colher (sopa) em 1 xícara de água quente, abafe 10 min.","f":["sem_mono"],"a":"Evidência científica limitada.","tag":null,"img":"fotos/494.jpg","id":"494"},
    {"c":"68","n":"Anis-Estrelado","cat":"Chás e Ervas","d":"Fruto seco em forma de estrela do Illicium verum. Aroma doce, semelhante ao da erva-doce.","b":["Uso tradicional reconhecido na Europa (EMA) para gases e tosse","Aromatiza chás, caldas, doces e carnes","Muito aromático: pouca quantidade basta"],"u":"1 estrela em 1 xícara de água quente, abafe 10 min.","f":["ema"],"a":"Compre somente de fornecedor confiável (há espécie tóxica parecida). Não dar a bebês.","tag":null,"img":"fotos/68.jpg","id":"68","step":10},
    {"c":"429","n":"Canela em Pau","cat":"Chás e Ervas","d":"Casca de canela enrolada em rolinhos.","b":["Dá sabor adocicado sem açúcar","Chás, caldas, arroz-doce e quentão","Dura mais que a canela em pó"],"u":"1 pau em 1 xícara de água fervente por 5 min.","f":["nccih_cinnamon"],"a":null,"tag":null,"img":"fotos/429.jpg","id":"429"},
    {"c":"518","n":"Capim-Limão (Capim-Santo)","cat":"Chás e Ervas","d":"Folhas secas de Cymbopogon citratus. Aroma cítrico de limão.","b":["Uso reconhecido pela ANVISA como calmante suave (ansiedade e insônia leves)","Uso reconhecido como auxiliar em cólicas leves","Chá refrescante, quente ou gelado"],"u":"1 colher (sopa) em 1 xícara de água quente, abafe 10 min.","f":["ff"],"a":null,"tag":null,"img":"fotos/518.jpg","id":"518"},
    {"c":"592","n":"Cavalinha","cat":"Chás e Ervas","d":"Partes aéreas secas de Equisetum arvense.","b":["Uso reconhecido pela ANVISA como diurético suave","Tradicionalmente usada em queixas urinárias leves","Rica em silício"],"u":"1 colher (sopa) em 1 xícara de água quente, abafe 10 min. Até 3 xícaras ao dia.","f":["ff"],"a":"Não use por mais de 4 semanas seguidas, nem com problemas cardíacos ou renais.","tag":null,"img":"fotos/592.jpg","id":"592"},
    {"c":"508","n":"Camomila em Flor","cat":"Chás e Ervas","d":"Flores secas de Matricaria chamomilla.","b":["Uso reconhecido pela ANVISA como calmante suave e auxiliar do sono","Uso reconhecido como auxiliar em cólicas e desconfortos digestivos leves","Chá suave, para todas as idades"],"u":"1 colher (sopa) em 1 xícara de água quente, abafe 10 min.","f":["ff","nccih_chamomile"],"a":"Evite se tiver alergia a plantas da família das margaridas.","tag":null,"img":"fotos/508.jpg","id":"508"},
    {"c":"726","n":"Espinheira-Santa","cat":"Chás e Ervas","d":"Folhas secas de Maytenus ilicifolia, planta nativa do Sul do Brasil.","b":["Uso reconhecido pela ANVISA como auxiliar em azia e má digestão","Planta medicinal brasileira do SUS (RENISUS)","Chá de sabor suave"],"u":"1 colher (sopa) em 1 xícara de água quente, abafe 10 min, antes das refeições.","f":["ff"],"a":"Evite na gravidez e amamentação.","tag":null,"img":"fotos/726.jpg","id":"726"},
    {"c":"501","n":"Mulungu","cat":"Chás e Ervas","d":"Casca seca de mulungu (Erythrina), árvore brasileira.","b":["Uso reconhecido pela ANVISA como auxiliar no alívio da ansiedade e insônia leves","Planta da medicina tradicional brasileira","Chá calmante"],"u":"1 colher (chá) em 1 xícara de água fervente por 5 min, à noite.","f":["ff"],"a":"Pode causar sonolência. Não associe a calmantes ou álcool.","tag":null,"img":"fotos/501.jpg","id":"501"},
    {"c":"596","n":"Passiflora (Maracujá)","cat":"Chás e Ervas","d":"Folhas secas de passiflora.","b":["Uso reconhecido pela ANVISA como auxiliar no alívio da ansiedade e insônia leves","Uma das plantas calmantes mais conhecidas","Chá suave"],"u":"1 colher (sopa) em 1 xícara de água quente, abafe 10 min, à noite.","f":["ff"],"a":"Pode causar sonolência. Evite na gravidez.","tag":null,"img":"fotos/596.jpg","id":"596"},
    {"c":"509","n":"Chá Verde","cat":"Chás e Ervas","d":"Folhas secas de Camellia sinensis, não fermentadas. Contêm cafeína e catequinas.","b":["Fonte de catequinas antioxidantes","Contém cafeína: ajuda na disposição e na atenção","Bebida tradicional milenar"],"u":"1 colher (chá) em 1 xícara de água a 80 °C (não fervente), por 3 min.","f":["nccih_greentea"],"a":"Contém cafeína. Evite à noite e na gravidez. Extratos concentrados podem afetar o fígado; o chá comum é seguro.","tag":null,"img":"fotos/509.jpg","id":"509"},
    {"c":"436","n":"Cravo-da-Índia","cat":"Chás e Ervas","d":"Botões florais secos de Syzygium aromaticum.","b":["Aroma intenso para chás, doces, caldas e carnes","Rico em eugenol, composto aromático","Especiaria de uso culinário tradicional"],"u":"Use 3 a 5 cravos por receita ou chá.","f":["taco"],"a":null,"tag":null,"img":"fotos/436.jpg","id":"436"},
    {"c":"517","n":"Hibisco","cat":"Chás e Ervas","d":"Cálices secos de Hibiscus sabdariffa. Chá vermelho de sabor ácido.","b":["Fonte de antocianinas, pigmentos antioxidantes","Chá sem cafeína, delicioso gelado","Estudos indicam efeito modesto na pressão arterial"],"u":"1 colher (sopa) em 1 xícara de água quente, abafe 5 min.","f":["nccih_hibiscus"],"a":"Evite na gravidez. Consulte o médico se usa remédios para pressão.","tag":null,"img":"fotos/517.jpg","id":"517"},
    {"c":"65","n":"Louro em Folhas","cat":"Chás e Ervas","d":"Folhas secas de louro (Laurus nobilis).","b":["Tempero indispensável do feijão, ensopados e molhos","Uso culinário tradicional como digestivo","Aroma que dispensa excesso de sal"],"u":"1 a 2 folhas no cozimento. Retire antes de servir.","f":["guia"],"a":null,"tag":null,"img":"fotos/65.jpg","id":"65","step":10},
    {"c":"504","n":"Melissa (Erva-Cidreira)","cat":"Chás e Ervas","d":"Folhas secas de Melissa officinalis.","b":["Uso reconhecido pela ANVISA como calmante suave e auxiliar do sono","Uso reconhecido como auxiliar em desconfortos digestivos leves","Chá de aroma cítrico e suave"],"u":"1 colher (sopa) em 1 xícara de água quente, abafe 10 min.","f":["ff"],"a":"Pode causar sonolência.","tag":null,"img":"fotos/504.jpg","id":"504"},
    {"c":"387","n":"Ameixa sem Caroço","cat":"Petiscos e Castanhas","d":"Ameixa seca desidratada, sem caroço.","b":["Rica em fibras e sorbitol, que ajudam o intestino","Doce natural para lanches","Fonte de potássio"],"u":"3 a 5 unidades ao dia.","f":["taco","efsa"],"a":null,"tag":null,"img":"fotos/387.jpg","id":"387"},
    {"c":"464","n":"Amêndoa Crua","cat":"Petiscos e Castanhas","d":"Amêndoa inteira com pele, crua.","b":["Fonte de vitamina E, magnésio e gorduras boas","Lanche que dá saciedade","Base para leite vegetal e farinha"],"u":"1 punhado (cerca de 20 unidades) ao dia.","f":["taco","efsa"],"a":null,"tag":null,"img":"fotos/464.jpg","id":"464"},
    {"c":"891","n":"Amêndoa Defumada","cat":"Petiscos e Castanhas","d":"Amêndoa torrada com sabor defumado.","b":["Petisco saboroso e crocante","Fonte de gorduras boas e proteínas","Ótima para aperitivos"],"u":"1 punhado ao dia. Pode conter sal.","f":["taco"],"a":null,"tag":null,"img":"fotos/891.jpg","id":"891"},
    {"c":"1057","n":"Amêndoa Laminada","cat":"Petiscos e Castanhas","d":"Amêndoa em lâminas finas.","b":["Crocância para bolos, saladas e iogurtes","Fonte de vitamina E e gorduras boas","Pronta para decorar"],"u":"Toste levemente na frigideira para realçar o sabor.","f":["taco"],"a":null,"tag":null,"img":"fotos/1057.jpg","id":"1057"},
    {"c":"388","n":"Amendoim Sabor Cebola e Salsa","cat":"Petiscos e Castanhas","d":"Amendoim crocante com cobertura sabor cebola e salsa.","b":["Petisco saboroso para momentos de lazer","Fonte de proteínas","Porção à vontade"],"u":"Consumo moderado: contém sal e cobertura.","f":["taco"],"a":null,"tag":null,"img":"fotos/388.jpg","id":"388"},
    {"c":"10","n":"Amendoim Sabor Churrasco","cat":"Petiscos e Castanhas","d":"Amendoim crocante com cobertura sabor churrasco.","b":["Petisco saboroso","Fonte de proteínas","Ótimo para reuniões"],"u":"Consumo moderado: contém sal e cobertura.","f":["taco"],"a":null,"tag":null,"img":"fotos/10.jpg","id":"10"},
    {"c":"390","n":"Amendoim Sabor Picante","cat":"Petiscos e Castanhas","d":"Amendoim crocante com cobertura picante.","b":["Petisco com ardência na medida","Fonte de proteínas","Ótimo para aperitivos"],"u":"Consumo moderado: contém sal e cobertura.","f":["taco"],"a":null,"tag":null,"img":"fotos/390.jpg","id":"390"},
    {"c":"466","n":"Amendoim Torrado sem Pele","cat":"Petiscos e Castanhas","d":"Amendoim torrado, sem pele e sem sal.","b":["Fonte de proteínas, gorduras boas e vitamina E","Base para pasta de amendoim caseira","Petisco sem sal"],"u":"1 punhado ao dia ou bata no processador para fazer pasta.","f":["taco"],"a":null,"tag":null,"img":"fotos/466.jpg","id":"466"},
    {"c":"756","n":"Amendoim Torrado sem Pele com Sal","cat":"Petiscos e Castanhas","d":"Amendoim torrado, sem pele e salgado.","b":["Petisco clássico","Fonte de proteínas e gorduras boas","Crocante"],"u":"1 punhado ao dia. Contém sal.","f":["taco"],"a":null,"tag":null,"img":"fotos/756.jpg","id":"756"},
    {"c":"1031","n":"Banana Chips","cat":"Petiscos e Castanhas","d":"Banana em fatias desidratadas e crocantes.","b":["Lanche crocante e prático","Fonte de potássio","Combina com iogurte e granola"],"u":"Pode conter açúcar ou óleo: confira o rótulo.","f":["taco"],"a":null,"tag":null,"img":"fotos/1031.jpg","id":"1031"},
    {"c":"534","n":"Batata Mexicana Cebola e Salsa","cat":"Petiscos e Castanhas","d":"Batata palha tipo mexicana, sabor cebola e salsa.","b":["Petisco crocante","Sabor de cebola e salsa","Para momentos de lazer"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/534.jpg","id":"534-cebola-e-salsa"},
    {"c":"534","n":"Batata Mexicana Original","cat":"Petiscos e Castanhas","d":"Batata palha tipo mexicana, sabor original.","b":["Petisco crocante","Sabor clássico","Para momentos de lazer"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/534.jpg","id":"534-original"},
    {"c":"534","n":"Batata Mexicana Churrasco","cat":"Petiscos e Castanhas","d":"Batata palha tipo mexicana, sabor churrasco.","b":["Petisco crocante","Sabor churrasco","Para momentos de lazer"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/534.jpg","id":"534-churrasco"},
    {"c":"918","n":"Biscoito de Arroz com Barbecue","cat":"Petiscos e Castanhas","d":"Biscoitinhos de arroz crocantes sabor barbecue.","b":["Petisco crocante à base de arroz","Petisco para aperitivos","Sabor barbecue"],"u":"Consumo moderado. Confira o rótulo sobre glúten.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/918.jpg","id":"918"},
    {"c":"394","n":"Castanha de Caju","cat":"Petiscos e Castanhas","d":"Castanha de caju torrada.","b":["Fonte de magnésio, zinco e gorduras boas","Lanche que dá saciedade","Base para cremes e molhos veganos"],"u":"1 punhado (cerca de 30 g) ao dia.","f":["taco"],"a":null,"tag":null,"img":"fotos/394.jpg","id":"394"},
    {"c":"393","n":"Castanha-do-Pará","cat":"Petiscos e Castanhas","d":"Castanha-do-brasil, nativa da Amazônia.","b":["A fonte alimentar mais rica em selênio","1 a 2 unidades por dia já cobrem a necessidade de selênio","Fonte de gorduras boas"],"u":"Coma no máximo 1 a 2 unidades por dia: em excesso, o selênio faz mal.","f":["ods_se","taco"],"a":null,"tag":null,"img":"fotos/393.jpg","id":"393"},
    {"c":"1450","n":"Chips de Frutas Tropicais","cat":"Petiscos e Castanhas","d":"Mix de frutas tropicais desidratadas e crocantes.","b":["Lanche doce e crocante","Frutas em formato prático","Combina com iogurte e granola"],"u":"Pode conter açúcar: confira o rótulo.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1450.jpg","id":"1450"},
    {"c":"1870","n":"Coco em Flocos","cat":"Petiscos e Castanhas","d":"Polpa de coco em flocos.","b":["Crocância e sabor de coco em granolas e doces","Fonte de fibras","Pode ser tostado"],"u":"Toste na frigideira para mais sabor.","f":["taco"],"a":null,"tag":null,"img":"fotos/1870.jpg","id":"1870"},
    {"c":"468","n":"Coco Ralado Médio","cat":"Petiscos e Castanhas","d":"Polpa de coco ralada e seca.","b":["Ingrediente básico de doces e bolos","Fonte de fibras","Sabor natural de coco"],"u":"Use em receitas doces e salgadas.","f":["taco"],"a":null,"tag":null,"img":"fotos/468.jpg","id":"468"},
    {"c":"583","n":"Damasco Desidratado","cat":"Petiscos e Castanhas","d":"Damasco seco, macio.","b":["Fonte de fibras e potássio","Contém betacaroteno (pró-vitamina A)","Doce natural para lanches"],"u":"3 a 5 unidades ao dia.","f":["taco"],"a":null,"tag":null,"img":"fotos/583.jpg","id":"583"},
    {"c":"1280","n":"Jaca Chips","cat":"Petiscos e Castanhas","d":"Jaca desidratada crocante.","b":["Petisco crocante de fruta","Sabor tropical","Lanche prático"],"u":"Pode conter açúcar ou óleo: confira o rótulo.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1280.jpg","id":"1280"},
    {"c":"550","n":"Laranja Desidratada em Rodelas","cat":"Petiscos e Castanhas","d":"Fatias de laranja desidratadas.","b":["Decoram drinks, chás, bolos e mesas","Aroma cítrico em infusões","Petisco de fruta"],"u":"Use em chás, águas saborizadas ou como decoração.","f":["taco"],"a":null,"tag":null,"img":"fotos/550.jpg","id":"550"},
    {"c":"252","n":"Limão Desidratado em Rodelas","cat":"Petiscos e Castanhas","d":"Fatias de limão desidratadas.","b":["Aroma cítrico para chás, drinks e águas saborizadas","Decoração natural","Longa durabilidade"],"u":"Adicione em água, chás ou drinks.","f":["taco"],"a":null,"tag":null,"img":"fotos/252.jpg","id":"252"},
    {"c":"274","n":"Milho Mel e Mostarda","cat":"Petiscos e Castanhas","d":"Petisco de milho crocante sabor mel e mostarda.","b":["Petisco agridoce e crocante","Para momentos de lazer","Porção à vontade"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/274.jpg","id":"274"},
    {"c":"893","n":"Mix de Castanhas Mediterrâneo","cat":"Petiscos e Castanhas","d":"Mistura de castanhas e frutas secas. Composição conforme rótulo.","b":["Variedade de gorduras boas, fibras e minerais","Lanche prático que dá saciedade","Ótimo para levar na bolsa"],"u":"1 punhado (cerca de 30 g) ao dia.","f":["taco","rotulo"],"a":null,"tag":null,"img":"fotos/893.jpg","id":"893"},
    {"c":"888","n":"Mix de Castanhas Premium","cat":"Petiscos e Castanhas","d":"Mistura selecionada de castanhas nobres. Composição conforme rótulo.","b":["Variedade de gorduras boas, proteínas e minerais","Lanche que dá saciedade","Petisco sofisticado"],"u":"1 punhado (cerca de 30 g) ao dia.","f":["taco","rotulo"],"a":null,"tag":null,"img":"fotos/888.jpg","id":"888"},
    {"c":"1791","n":"Mix de Frutas Vermelhas","cat":"Petiscos e Castanhas","d":"Mistura de frutas vermelhas desidratadas. Composição conforme rótulo.","b":["Fonte de antocianinas, pigmentos antioxidantes","Doce natural para iogurtes e granolas","Lanche prático"],"u":"Pode conter açúcar: confira o rótulo.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1791.jpg","id":"1791"},
    {"c":"928","n":"Mix de Vegetais","cat":"Petiscos e Castanhas","d":"Legumes desidratados crocantes. Composição conforme rótulo.","b":["Petisco crocante de legumes","Legumes em formato de petisco","Lanche prático"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/928.jpg","id":"928"},
    {"c":"587","n":"Nozes Quartz","cat":"Petiscos e Castanhas","d":"Nozes em quartos (pedaços).","b":["30 g de nozes por dia ajudam na saúde dos vasos sanguíneos (alegação aprovada na UE)","Fonte de ômega-3 vegetal (ALA)","Crocância em saladas, bolos e iogurtes"],"u":"1 punhado (cerca de 30 g) ao dia.","f":["efsa","taco"],"a":null,"tag":null,"img":"fotos/587.jpg","id":"587"},
    {"c":"6","n":"Pimentinha","cat":"Petiscos e Castanhas","d":"Petisco crocante picante. Composição conforme rótulo.","b":["Petisco picante e crocante","Para aperitivos","Porção à vontade"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/6.jpg","id":"6"},
    {"c":"645","n":"Proteína de Soja","cat":"Petiscos e Castanhas","d":"Proteína texturizada de soja (PTS), seca.","b":["Fonte de proteína vegetal","Substitui a carne moída em receitas","Rende muito depois de hidratada"],"u":"Hidrate em água quente por 10 min, esprema e tempere.","f":["taco"],"a":null,"tag":null,"img":"fotos/645.jpg","id":"645"},
    {"c":"574","n":"Provolone Desidratado","cat":"Petiscos e Castanhas","d":"Cubinhos de queijo provolone desidratados e crocantes.","b":["Petisco crocante de queijo","Fonte de proteínas e cálcio","Ótimo para aperitivos"],"u":"Consumo moderado: contém sal.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/574.jpg","id":"574"},
    {"c":"1146","n":"Provolone Desidratado com Goiabada","cat":"Petiscos e Castanhas","d":"Cubinhos de provolone desidratado com goiabada.","b":["Combinação clássica de queijo com goiabada","Petisco doce e salgado","Fonte de proteínas e cálcio"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1146.jpg","id":"1146"},
    {"c":"408","n":"Tâmara sem Caroço","cat":"Petiscos e Castanhas","d":"Tâmara seca, macia e muito doce.","b":["Doce natural que substitui o açúcar em receitas","Fonte de fibras e potássio","Energia rápida antes do treino"],"u":"2 a 3 unidades ao dia ou batidas em receitas.","f":["taco"],"a":null,"tag":null,"img":"fotos/408.jpg","id":"408"},
    {"c":"5","n":"Tortilha Queijo Nacho","cat":"Petiscos e Castanhas","d":"Chips de tortilha de milho sabor queijo nacho.","b":["Petisco crocante","Acompanha guacamole e molhos","Para momentos de lazer"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/5.jpg","id":"5"},
    {"c":"414","n":"Uva-Passa Preta","cat":"Petiscos e Castanhas","d":"Uva seca escura.","b":["Doce natural para receitas e lanches","Fonte de fibras, potássio e ferro","Combina com arroz, saladas e granolas"],"u":"1 colher (sopa) em saladas, arroz ou iogurte.","f":["taco"],"a":null,"tag":null,"img":"fotos/414.jpg","id":"414"},
    {"c":"759","n":"Xerém de Amendoim","cat":"Petiscos e Castanhas","d":"Amendoim torrado e picado.","b":["Crocância para doces, sorvetes e saladas","Fonte de proteínas e gorduras boas","Pronto para usar"],"u":"Use para cobrir doces e bolos.","f":["taco"],"a":null,"tag":null,"img":"fotos/759.jpg","id":"759"},
    {"c":"760","n":"Xerém de Castanha de Caju","cat":"Petiscos e Castanhas","d":"Castanha de caju picada.","b":["Crocância para doces, saladas e pratos salgados","Fonte de magnésio e gorduras boas","Pronto para usar"],"u":"Use para cobrir doces, bolos e saladas.","f":["taco"],"a":null,"tag":null,"img":"fotos/760.jpg","id":"760"},
    {"c":"1","n":"Balas de Ursinho sem Açúcar com Xilitol","cat":"Drágeas e Guloseimas","d":"Balas de goma em formato de ursinho, adoçadas com xilitol.","b":["Sem açúcar","O xilitol não causa cáries","Doce para quem controla o açúcar"],"u":"Consumo moderado: em excesso, o xilitol pode causar desconforto intestinal.","f":["efsa","rotulo"],"a":"Tóxico para cães.","tag":null,"img":"fotos/1.jpg","id":"1"},
    {"c":"1663","n":"Drágea Abacaxi com Coco e Chocolate Branco","cat":"Drágeas e Guloseimas","d":"Abacaxi desidratado com coco coberto com chocolate branco.","b":["Combinação tropical e cremosa","Mimo para momentos especiais","Ótimo para presentear"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"","id":"1663"},
    {"c":"1788","n":"Drágea de Amêndoa Zero Açúcar","cat":"Drágeas e Guloseimas","d":"Amêndoas cobertas com chocolate sem adição de açúcar.","b":["Sem adição de açúcar","Amêndoa: fonte de gorduras boas e vitamina E","Doce mais equilibrado"],"u":"Consumo moderado. Confira o rótulo.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1788.jpg","id":"1788"},
    {"c":"1122","n":"Drágea de Amêndoa com Limão Siciliano","cat":"Drágeas e Guloseimas","d":"Amêndoas com cobertura sabor limão siciliano.","b":["Sabor cítrico e refrescante","Amêndoa crocante por dentro","Ótimo para presentear"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1122.jpg","id":"1122"},
    {"c":"873","n":"Drágea de Banana com Chocolate 70%","cat":"Drágeas e Guloseimas","d":"Banana desidratada coberta com chocolate 70% cacau.","b":["Chocolate 70%: mais cacau e menos açúcar","Fruta com chocolate","Doce para o fim da refeição"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/873.jpg","id":"873"},
    {"c":"889","n":"Drágea de Banana Palito com Chocolate 70%","cat":"Drágeas e Guloseimas","d":"Palitos de banana desidratada cobertos com chocolate 70%.","b":["Chocolate 70%: mais cacau e menos açúcar","Formato palito, prático","Fruta com chocolate"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/889.jpg","id":"889"},
    {"c":"879","n":"Drágea de Caju com Chocolate 70%","cat":"Drágeas e Guloseimas","d":"Castanha de caju coberta com chocolate 70% cacau.","b":["Chocolate 70%: mais cacau e menos açúcar","Castanha crocante por dentro","Doce para o fim da refeição"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/879.jpg","id":"879"},
    {"c":"16","n":"Drágea de Castanha-do-Pará com Coco Queimado","cat":"Drágeas e Guloseimas","d":"Castanha-do-pará com cobertura de coco queimado.","b":["Sabor de coco caramelizado","Castanha-do-pará: fonte de selênio","Ótimo para presentear"],"u":"Consumo moderado.","f":["rotulo","ods_se"],"a":null,"tag":null,"img":"fotos/16.jpg","id":"16"},
    {"c":"1787","n":"Drágea de Morango Chips com Chocolate Branco","cat":"Drágeas e Guloseimas","d":"Morango desidratado crocante coberto com chocolate branco.","b":["Fruta crocante com chocolate cremoso","Sabor delicado","Ótimo para presentear"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"","id":"1787"},
    {"c":"1688","n":"Drágea de Cereja com Chocolate 70%","cat":"Drágeas e Guloseimas","d":"Cereja desidratada coberta com chocolate 70% cacau.","b":["Chocolate 70%: mais cacau e menos açúcar","Fruta levemente ácida com chocolate","Doce para momentos especiais"],"u":"Consumo moderado.","f":["rotulo"],"a":null,"tag":null,"img":"","id":"1688"},
    {"c":"1174","n":"Gotas de Chocolate 0% Açúcar 70% Cacau","cat":"Drágeas e Guloseimas","d":"Gotas de chocolate 70% cacau sem adição de açúcar.","b":["Sem adição de açúcar","Resistem ao forno: ideais para cookies e bolos","70% cacau"],"u":"Use em receitas ou como doce. Confira o rótulo.","f":["rotulo"],"a":null,"tag":null,"img":"fotos/1174.jpg","id":"1174"}
  ]
};
